root:
  - changed-files:
      - any-glob-to-any-file: '*'

documentation:
  - changed-files:
      - any-glob-to-any-file: '*.md'

chore:
  - any:
      - changed-files:
          - any-glob-to-all-files: ['*']
      - head-branch:
          - '^chore'

feature:
  - head-branch:
      - '^feat'

fix:
  - head-branch:
      - '^fix'
      - '^hotfix'

refactor:
  - head-branch:
      - '^refactor'

test:
  - head-branch:
      - '^test'

revert:
  - head-branch:
      - '^revert'

style:
  - changed-files:
      - any-glob-to-any-file: '*.scss'

sprint1:
  - pull-request-title: 'ECOMM-1'

sprint2:
  - pull-request-title: 'ECOMM-2'

sprint3:
  - pull-request-title: 'ECOMM-3'

sprint4:
  - pull-request-title: 'ECOMM-4'
