type CountryCodes = {
  [countryName: string]: string;
};

const COUNTRIES_LIST: Record<string, CountryCodes> = {
  en: {
    Afghanistan: 'AF',
    Albania: 'AL',
    Algeria: 'DZ',
    Andorra: 'AD',
    Angola: 'AO',
    'Antigua and Barbuda': 'AG',
    Argentina: 'AR',
    Armenia: 'AM',
    Australia: 'AU',
    Austria: 'AT',
    Azerbaijan: 'AZ',
    Bahamas: 'BS',
    Bahrain: 'BH',
    Bangladesh: 'BD',
    Barbados: 'BB',
    Belarus: 'BY',
    Belgium: 'BE',
    Belize: 'BZ',
    Benin: 'BJ',
    Bhutan: 'BT',
    Bolivia: 'BO',
    'Bosnia and Herzegovina': 'BA',
    Botswana: 'BW',
    Brazil: 'BR',
    Brunei: 'BN',
    Bulgaria: 'BG',
    'Burkina Faso': 'BF',
    Burundi: 'BI',
    'Cabo Verde': 'CV',
    Cambodia: 'KH',
    Cameroon: 'CM',
    Canada: 'CA',
    'Central African Republic': 'CF',
    Chad: 'TD',
    Chile: 'CL',
    China: 'CN',
    'Christmas Island': 'CX',
    'Cocos (Keeling) Islands': 'CC',
    Colombia: 'CO',
    Comoros: 'KM',
    'Congo, Democratic Republic of the': 'CD',
    'Congo, Republic of the': 'CG',
    'Costa Rica': 'CR',
    Croatia: 'HR',
    Cuba: 'CU',
    Curaçao: 'CW',
    Cyprus: 'CY',
    'Czech Republic': 'CZ',
    "Côte d'Ivoire": 'CI',
    Denmark: 'DK',
    Djibouti: 'DJ',
    Dominica: 'DM',
    'Dominican Republic': 'DO',
    Ecuador: 'EC',
    Egypt: 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    Eritrea: 'ER',
    Estonia: 'EE',
    Eswatini: 'SZ',
    Ethiopia: 'ET',
    Fiji: 'FJ',
    Finland: 'FI',
    France: 'FR',
    Gabon: 'GA',
    Gambia: 'GM',
    Georgia: 'GE',
    Germany: 'DE',
    Ghana: 'GH',
    Greece: 'GR',
    Grenada: 'GD',
    Guatemala: 'GT',
    Guinea: 'GN',
    'Guinea-Bissau': 'GW',
    Guyana: 'GY',
    Haiti: 'HT',
    Honduras: 'HN',
    Hungary: 'HU',
    Iceland: 'IS',
    India: 'IN',
    Indonesia: 'ID',
    Iran: 'IR',
    Iraq: 'IQ',
    Ireland: 'IE',
    Israel: 'IL',
    Italy: 'IT',
    Jamaica: 'JM',
    Japan: 'JP',
    Jordan: 'JO',
    Kazakhstan: 'KZ',
    Kenya: 'KE',
    Kiribati: 'KI',
    'Korea, North': 'KP',
    'Korea, South': 'KR',
    Kosovo: 'XK',
    Kuwait: 'KW',
    Kyrgyzstan: 'KG',
    Laos: 'LA',
    Latvia: 'LV',
    Lebanon: 'LB',
    Lesotho: 'LS',
    Liberia: 'LR',
    Libya: 'LY',
    Liechtenstein: 'LI',
    Lithuania: 'LT',
    Luxembourg: 'LU',
    Madagascar: 'MG',
    Malawi: 'MW',
    Malaysia: 'MY',
    Maldives: 'MV',
    Mali: 'ML',
    Malta: 'MT',
    'Marshall Islands': 'MH',
    Mauritania: 'MR',
    Mauritius: 'MU',
    Mexico: 'MX',
    Micronesia: 'FM',
    Moldova: 'MD',
    Monaco: 'MC',
    Mongolia: 'MN',
    Montenegro: 'ME',
    Morocco: 'MA',
    Mozambique: 'MZ',
    Myanmar: 'MM',
    Namibia: 'NA',
    Nauru: 'NR',
    Nepal: 'NP',
    Netherlands: 'NL',
    'New Zealand': 'NZ',
    Nicaragua: 'NI',
    Niger: 'NE',
    Nigeria: 'NG',
    'North Macedonia': 'MK',
    Norway: 'NO',
    Oman: 'OM',
    Pakistan: 'PK',
    Palau: 'PW',
    Palestine: 'PS',
    Panama: 'PA',
    'Papua New Guinea': 'PG',
    Paraguay: 'PY',
    Peru: 'PE',
    Philippines: 'PH',
    Poland: 'PL',
    Portugal: 'PT',
    Qatar: 'QA',
    Romania: 'RO',
    Russia: 'RU',
    Rwanda: 'RW',
    'Saint Kitts and Nevis': 'KN',
    'Saint Lucia': 'LC',
    'Saint Vincent and the Grenadines': 'VC',
    Samoa: 'WS',
    'San Marino': 'SM',
    'Sao Tome and Principe': 'ST',
    'Saudi Arabia': 'SA',
    Senegal: 'SN',
    Serbia: 'RS',
    Seychelles: 'SC',
    'Sierra Leone': 'SL',
    Singapore: 'SG',
    Slovakia: 'SK',
    Slovenia: 'SI',
    'Solomon Islands': 'SB',
    Somalia: 'SO',
    'South Africa': 'ZA',
    'South Sudan': 'SS',
    Spain: 'ES',
    'Sri Lanka': 'LK',
    Sudan: 'SD',
    Suriname: 'SR',
    Sweden: 'SE',
    Switzerland: 'CH',
    Syria: 'SY',
    Taiwan: 'TW',
    Tajikistan: 'TJ',
    Tanzania: 'TZ',
    Thailand: 'TH',
    'Timor-Leste': 'TL',
    Togo: 'TG',
    Tonga: 'TO',
    'Trinidad and Tobago': 'TT',
    Tunisia: 'TN',
    Turkey: 'TR',
    Turkmenistan: 'TM',
    Tuvalu: 'TV',
    Uganda: 'UG',
    Ukraine: 'UA',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'GB',
    'United States': 'US',
    Uruguay: 'UY',
    Uzbekistan: 'UZ',
    Vanuatu: 'VU',
    'Vatican City': 'VA',
    Venezuela: 'VE',
    Vietnam: 'VN',
    Yemen: 'YE',
    Zambia: 'ZM',
    Zimbabwe: 'ZW',
  },
  ru: {
    Австралия: 'AU',
    Австрия: 'AT',
    Азербайджан: 'AZ',
    Албания: 'AL',
    Алжир: 'DZ',
    Ангола: 'AO',
    Андорра: 'AD',
    'Антигуа и Барбуда': 'AG',
    Аргентина: 'AR',
    Армения: 'AM',
    Афганистан: 'AF',
    Багамы: 'BS',
    Бангладеш: 'BD',
    Барбадос: 'BB',
    Бахрейн: 'BH',
    Беларусь: 'BY',
    Белиз: 'BZ',
    Бельгия: 'BE',
    Бенин: 'BJ',
    Болгария: 'BG',
    Боливия: 'BO',
    'Босния и Герцеговина': 'BA',
    Ботсвана: 'BW',
    Бразилия: 'BR',
    Бруней: 'BN',
    'Буркина-Фасо': 'BF',
    Бурунди: 'BI',
    Бутан: 'BT',
    Вануату: 'VU',
    Ватикан: 'VA',
    Великобритания: 'GB',
    Венгрия: 'HU',
    Венесуэла: 'VE',
    'Восточный Тимор': 'TL',
    Вьетнам: 'VN',
    Габон: 'GA',
    Гаити: 'HT',
    Гайана: 'GY',
    Гамбия: 'GM',
    Гана: 'GH',
    Гватемала: 'GT',
    Гвинея: 'GN',
    'Гвинея-Бисау': 'GW',
    Германия: 'DE',
    Гондурас: 'HN',
    Гренада: 'GD',
    Греция: 'GR',
    Грузия: 'GE',
    Дания: 'DK',
    'Демократическая Республика Конго': 'CD',
    Джибути: 'DJ',
    Доминика: 'DM',
    'Доминиканская Республика': 'DO',
    Египет: 'EG',
    Замбия: 'ZM',
    Зимбабве: 'ZW',
    Израиль: 'IL',
    Индия: 'IN',
    Индонезия: 'ID',
    Иордания: 'JO',
    Ирак: 'IQ',
    Иран: 'IR',
    Ирландия: 'IE',
    Исландия: 'IS',
    Испания: 'ES',
    Италия: 'IT',
    Йемен: 'YE',
    КНДР: 'KP',
    'Кабо-Верде': 'CV',
    Казахстан: 'KZ',
    Камбоджа: 'KH',
    Камерун: 'CM',
    Канада: 'CA',
    Катар: 'QA',
    Кения: 'KE',
    Кипр: 'CY',
    Киргизия: 'KG',
    Кирибати: 'KI',
    Китай: 'CN',
    'Кокосовые (Килинг) острова': 'CC',
    Колумбия: 'CO',
    'Коморские острова': 'KM',
    Косово: 'XK',
    'Коста-Рика': 'CR',
    'Кот-д’Ивуар': 'CI',
    Куба: 'CU',
    Кувейт: 'KW',
    Кюрасао: 'CW',
    Лаос: 'LA',
    Латвия: 'LV',
    Лесото: 'LS',
    Либерия: 'LR',
    Ливан: 'LB',
    Ливия: 'LY',
    Литва: 'LT',
    Лихтенштейн: 'LI',
    Люксембург: 'LU',
    Маврикий: 'MU',
    Мавритания: 'MR',
    Мадагаскар: 'MG',
    Малави: 'MW',
    Малайзия: 'MY',
    Мали: 'ML',
    Мальдивы: 'MV',
    Мальта: 'MT',
    Марокко: 'MA',
    'Маршалловы острова': 'MH',
    Мексика: 'MX',
    Микронезия: 'FM',
    Мозамбик: 'MZ',
    Молдавия: 'MD',
    Монако: 'MC',
    Монголия: 'MN',
    Мьянма: 'MM',
    Намибия: 'NA',
    Науру: 'NR',
    Непал: 'NP',
    Нигер: 'NE',
    Нигерия: 'NG',
    Нидерланды: 'NL',
    Никарагуа: 'NI',
    'Новая Зеландия': 'NZ',
    Норвегия: 'NO',
    'Объединенные Арабские Эмираты': 'AE',
    Оман: 'OM',
    'Остров Рождества': 'CX',
    Пакистан: 'PK',
    Палау: 'PW',
    Палестина: 'PS',
    Панама: 'PA',
    'Папуа — Новая Гвинея': 'PG',
    Парагвай: 'PY',
    Перу: 'PE',
    Польша: 'PL',
    Португалия: 'PT',
    'Республика Конго': 'CG',
    'Республика Корея': 'KR',
    Россия: 'RU',
    Руанда: 'RW',
    Румыния: 'RO',
    Сальвадор: 'SV',
    Самоа: 'WS',
    'Сан-Марино': 'SM',
    'Сан-Томе и Принсипи': 'ST',
    'Саудовская Аравия': 'SA',
    Свазиленд: 'SZ',
    'Северная Македония': 'MK',
    'Сейшельские Острова': 'SC',
    Сенегал: 'SN',
    'Сент-Винсент и Гренадины': 'VC',
    'Сент-Китс и Невис': 'KN',
    'Сент-Люсия': 'LC',
    Сербия: 'RS',
    Сингапур: 'SG',
    Сирия: 'SY',
    Словакия: 'SK',
    Словения: 'SI',
    'Соединенные Штаты': 'US',
    'Соломоновы Острова': 'SB',
    Сомали: 'SO',
    Судан: 'SD',
    Суринам: 'SR',
    'Сьерра-Леоне': 'SL',
    Таджикистан: 'TJ',
    Таиланд: 'TH',
    Тайвань: 'TW',
    Танзания: 'TZ',
    Того: 'TG',
    Тонга: 'TO',
    'Тринидад и Тобаго': 'TT',
    Тувалу: 'TV',
    Тунис: 'TN',
    Туркменистан: 'TM',
    Турция: 'TR',
    Уганда: 'UG',
    Узбекистан: 'UZ',
    Украина: 'UA',
    Уругвай: 'UY',
    Фиджи: 'FJ',
    Филиппины: 'PH',
    Финляндия: 'FI',
    Франция: 'FR',
    Хорватия: 'HR',
    'Центральноафриканская Республика': 'CF',
    Чад: 'TD',
    Черногория: 'ME',
    'Чешская Республика': 'CZ',
    Чили: 'CL',
    Швейцария: 'CH',
    Швеция: 'SE',
    'Шри-Ланка': 'LK',
    Эквадор: 'EC',
    'Экваториальная Гвинея': 'GQ',
    Эритрея: 'ER',
    Эстония: 'EE',
    Эфиопия: 'ET',
    'Южная Африка': 'ZA',
    'Южный Судан': 'SS',
    Ямайка: 'JM',
    Япония: 'JP',
  },
} as const;

export default COUNTRIES_LIST;
