const MEDIATOR_EVENT = {
  REDRAW_ADDRESSES: 'REDRAW_ADDRESSES',
  REDRAW_PRODUCTS: 'REDRAW_PRODUCTS',
  REDRAW_USER_ADDRESS: 'REDRAW_USER_ADDRESS',
  REDRAW_USER_INFO: 'REDRAW_USER_INFO',
} as const;

export default MEDIATOR_EVENT;
