const MEDIATOR_EVENT = {
  CLEAR_CATALOG_SEARCH: 'CLEAR_CATALOG_SEARCH',
  REDRAW_PRODUCTS: 'REDRAW_PRODUCTS',
  REDRAW_USER_ADDRESS: 'REDRAW_USER_ADDRESS',
  REDRAW_USER_INFO: 'REDRAW_USER_INFO',
} as const;

export default MEDIATOR_EVENT;
