const SVG_DETAILS = {
  ARROW_UP: 'arrowUp',
  BILL: 'bill',
  BIN: 'bin',
  CART: 'cart',
  CLOSE_EYE: 'closeEye',
  COPY: 'copy',
  DARK: 'dark',
  DELETE: 'delete',
  DELIVERY: 'delivery',
  EDIT: 'edit',
  FILL_HEART: 'heartFill',
  GO_DETAILS: 'arrow',
  KEY: 'key',
  LEAVES: 'leaves',
  LIGHT: 'light',
  LOGO: 'logo',
  NOT_FOUND: 'notFound',
  OPEN_EYE: 'openEye',
  PROFILE: 'userCircle',
  SVG_URL: 'http://www.w3.org/2000/svg',
  SWITCH_LANGUAGE: {
    en: 'en',
    ru: 'ru',
  },
  TRUCK: 'truck',
  WALLET: 'wallet',
} as const;

export default SVG_DETAILS;
